
spring:
#   application:
#     name: provider-movie
  security:
    user:
      name: eureka
      password: 123456
  datasource:  
    driver-class-name: com.mysql.jdbc.Driver    
    url: jdbc:mysql://120.26.52.92:13306/csxcx?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false    
    username: wnxcx                                  
    password: XCX-test)^(&16
      
      
mybatis:
  mapper-locations: classpath:*Mapper.xml
  typeAliasesPackage: com.meituan.maoyan.common.entity


#全局日志  
logging:
  level:
    root: info



    
